Vagrant.configure("2") do |config|
  # Share the data folder - runs outside the machines
  config.vm.synced_folder "./data", "/root/data", :mount_options => ["dmode=777", "fmode=666"]

  # First to run
  config.vm.define "maugrim1" do |maugrim1|
    maugrim1.vm.box = "bento/ubuntu-18.04"
    maugrim1.vm.hostname = "Maugrim1"
    maugrim1.vm.provider "virtualbox" do |vb|
    end
    config.vm.provision "shell", path: "./data/install.sh"
    config.vm.network "private_network", ip: "192.168.56.79"
  end
end
