Vagrant.configure("2") do |config|

	# Share the data folder - runs outside the machines
	config.vm.synced_folder "./data", "/root/data", :mount_options => ["dmode=777", "fmode=666"]

	# First to run
	config.vm.define "xaphania" do |xaphania|
		xaphania.vm.box = "bento/ubuntu-18.04"
		xaphania.vm.hostname = "Xaphania"
		xaphania.vm.provider "virtualbox" do |vb|
		end
		config.vm.provision "shell", path: "./data/install.sh"
    	config.vm.network "private_network", ip: "192.168.56.30"
	end
end