Vagrant.configure("2") do |config|

	# Share the data folder - runs outside the machines
	config.vm.synced_folder "./data", "/root/data", :mount_options => ["dmode=777", "fmode=666"]

	# First to run
	config.vm.define "test" do |test|
		test.vm.box = "bento/ubuntu-18.04"
		test.vm.hostname = "Test"
		test.vm.provider "virtualbox" do |vb|
		end
		config.vm.provision "shell", path: "./data/install.sh"
    	#config.vm.network "private_network", ip: "10.0.2.10"
		config.vm.network "private_network", ip: "192.168.56.107" #, virtualbox__intnet: "InternalNet"
	end
end