Vagrant.configure("2") do |config|
  # Share the data folder - runs outside the machines
  config.vm.synced_folder "./data", "/root/data", :mount_options => ["dmode=777", "fmode=666"]

  # First to run
  config.vm.define "kirjava1" do |kirjava1|
    kirjava1.vm.box = "bento/ubuntu-18.04"
    kirjava1.vm.hostname = "Kirjava1"
    kirjava1.vm.provider "virtualbox" do |vb|
    end
    config.vm.provision "shell", path: "./data/install.sh"
    config.vm.network "private_network", ip: "192.168.56.78"
  end
end
